# Write multiple line qr code and then convert into base64 then make a qr code
'''
multi_line_input = ""

print("Enter the data to be Encoded or type 'done' to finish: ")

while True:
    line = input()
    if line.lower() == "done":
        break
    multi_line_input += line + "\n"
multi_line_input = multi_line_input.rstrip("\n")
print(multi_line_input)
'''
'''
a = 'iVBORw0KGgoAAAANSUhEUgAAAcIAAAHCCAIAAADzel4SAAAJZ0lEQVR4nO3dQW4jRxBFQcuYexs+Ob2dVcPwQzmzmhF7iS2KfKjNR/18Pp8/APiv/px+AIC7yShAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAya+vF/75+2fqpQ/5/PX5zz977t0oT1WUv+j5mXe+V1N/785P3ZSpT7vTKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQDK2Yno2tUZ4VlYfZYtybm2y86mendv8TC2Rzu2Uivd9B89xGgVIZBQgkVGAREYBEhkFSGQUIJFRgERGARIZBUiWrpie7byN59xv3rknefa+Zz63cXq2c+N043fwHKdRgERGARIZBUhkFCCRUYBERgESGQVIZBQgkVGA5MoV0/ucu0Foaj+zc+XyviXSzo3Tt3EaBUhkFCCRUYBERgESGQVIZBQgkVGAREYBEhkFSKyYLjC1Jtq5njrnxmdmA6dRgERGARIZBUhkFCCRUYBERgESGQVIZBQgkVGA5MoV0403zEytiYqd9/xM3adUfvPOZy52PtUUp1GAREYBEhkFSGQUIJFRgERGARIZBUhkFCCRUYBk6Yrp2262OXfr0dQ9TucWUDuf+cafffZt38HCaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCAZWzG5y+V35xYjU3uhG/+/O//enZ8Nfuc0CpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiRjK6adN72U3/xsan2x87alneuac+/Vja+7c7W1k9MoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChA8vP5bLzb5EZT66lvW8g8m1qpPXvfUz3beV/WOU6jAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAydiKaepGnZ1rovfdTLXzL7rxNq1nN95c9Gzn+/zMaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCAZu4tpyrfdPjT1VFP3GhVT91YVNz5VYcUE8EIyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJGMrpp07h53bm6l1zbn/0Tk7b5fauY+68ZNjxQTwQjIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJjAIkMgqQyChAIqMAiYwCJjAIkMgqQyChAIqMAiYwCJjAIkMgqQyChAIqMAiYwCJjAIkMgqQyChAIqMAiYwCJjAIkMgqQyChAIqMAyT+DK7hBfYD72gAAAABJRU5ErkJggg=='
import qrcode
from PIL import Image
qr = qrcode.QRCode(version=1, box_size=10, error_correction = qrcode.constants.ERROR_CORRECT_H, border= 4,)
qr.add_data(a)
qr.make(fit=True)
img = qr.make_image(fill_color="green", back_color= 'white')
img.save("encry_explore.png")

import base64
# Open the image file in binary mode
with open('explore.png', 'rb') as image_file:
    # Read the binary data of the image
    binary_data = image_file.read()
# Encode the binary data into Base64
base64_encoded = base64.b64encode(binary_data)
# Convert the result to a string (if needed)
base64_encoded_str = base64_encoded.decode('utf-8')
# Print the Base64-encoded image data
print(base64_encoded_str)
'''
'''
import base64

# Open the image file in binary mode
with open('explore.png', 'rb') as image_file:
    # Read the binary data of the image
    binary_data = image_file.read()

# Encode the binary data into Base64
base64_encoded = base64.b64encode(binary_data)

# Convert the result to a string (if needed)
base64_encoded_str = base64_encoded.decode('utf-8')

# Print or use the Base64-encoded string
print(base64_encoded_str)
'''
a = 'iVBORw0KGgoAAAANSUhEUgAAAcIAAAHCCAIAAADzel4SAAAJZ0lEQVR4nO3dQW4jRxBFQcuYexs+Ob2dVcPwQzmzmhF7iS2KfKjNR/18Pp8/APiv/px+AIC7yShAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAya+pF/75+2fqpQ/5/PX5zz977t0oT1WUv+j5mXe+V1N/785P3ZSpT7vTKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQDK2Yno2tUZ4VlYfZYtybm2y86mendv8TC2Rzu2Uivd9B89xGgVIZBQgkVGAREYBEhkFSGQUIJFRgERGARIZBUiWrpie7byN59xv3rknefa+Zz63cXq2c+N043fwHKdRgERGARIZBUhkFCCRUYBERgESGQVIZBQgkVGA5MoV0/ucu0Foaj+zc+XyviXSzo3Tt3EaBUhkFCCRUYBERgESGQVIZBQgkVGAREYBEhkFSKyYLjC1Jtq5njrnxmdmA6dRgERGARIZBUhkFCCRUYBERgESGQVIZBQgkVGA5MoV0403zEytiYqd9/xM3adUfvPOZy52PtUUp1GAREYBEhkFSGQUIJFRgERGARIZBUhkFCCRUYBk6Yrp2262OXfr0dQ9TucWUDuf+cafffZt38HCaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCAZWzG5y+V35xYjU3uhG/+/O//enZ8Nfuc0CpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkCy9i+mcqRtmdi5knk3dEXTutqVnN/7mojzV1Gpr5/LKaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCAZWzFN3TBz450559ZEU6ae6n3v5PsWbjdyGgVIZBQgkVGAREYBEhkFSGQUIJFRgERGARIZBUjGVkw3ronOKe/G1B7s3J05U7fxlHdy6t0odt5rdCOnUYBERgESGQVIZBQgkVGAREYBEhkFSGQUIJFRgGTpXUxT+5lv8747c6Y+G1M7pZ3fhZ33kp3jNAqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpAsvYtpagVRuG/n35va7Zz72fKbz31yyvs89cm5cVnnNAqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpD8fD5vW7kU79v8FDtvxNq5+Nr5PyqmFlA7b1t65jQKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQjN3FNHWjTrHzmXf+veU3P5t6n6fWU+fugHq2cx+1k9MoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAMnYX09SOpbhxL3TO1KZraqd047Lu2dTn6sZv6DOnUYBERgESGQVIZBQgkVGAREYBEhkFSGQUIJFRgGTsLqadblyqTO2Fzimv+75bns7dp7RzO7dzs/fMaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCBZehfTznXNuaXKOTuXOcWN9xrt3KGd+5btXPSd4zQKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQLL2L6cYFxbOpRdDOG4R2/kU3mnonp1535//XaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCAZu4tpyrfdPjT1VFP3GhVT91YVNz5VYcUE8EIyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJGMrpp07h53bm6l1zbn/0Tk7b5fauY+68ZNjxQTwQjIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkS+9imtpX3Hh3zY0rl/K659z4uXrf6+78hj5zGgVIZBQgkVGAREYBEhkFSGQUIJFRgERGARIZBUiuXDE9u3G5UV732bfdTXTuZ8+58amKnd/uwmkUIJFRgERGARIZBUhkFCCRUYBERgESGQVIZBQgWbpiOmfnIqg4t+p5NvWbd9q5+TlnanllxQTwQjIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkYyumqft2inMLqBv/oik7b5d6duPdUzvvNJt65mdOowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAMmv6Qf4v+28i2nncmPn3zu1vDr3zDt3Sjd+U6Y4jQIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiRjK6adN72U3/xsan2x87alneuac+/Vja+7c7W1k9MoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChA8vP5bLzb5EZT66lvW8g8m1qpPXvfUz3beV/WOU6jAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAydiKaepGnZ1rovfdTLXzL7rxNq1nN95c9Gzn+/zMaRQgkVGAREYBEhkFSGQUIJFRgERGARIZBUhkFCBxF9P/ZOeayBLp37txL7TzP3jj6z5zGgVIZBQgkVGAREYBEhkFSGQUIJFRgERGARIZBUh+Tb3wjZuQZ1MLmXObn2fuNfrdzvvBys9+27KucBoFSGQUIJFRgERGARIZBUhkFCCRUYBERgESGQVIxlZMz3ZuFc4tgnbePlRMbat22vlunPtsvG+n9MxpFCCRUYBERgESGQVIZBQgkVGAREYBEhkFSGQUIFm6Yno2tSY658ZbcXa+bnHuvz91y9O3rcWmOI0CJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkV66YbjS129m5F9q5cdq5+dm5cCtuvG3pmdMoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAYsW0wtSu49xe6Ny65n123gE1ZWpbVTiNAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJFeumHYuGYpzdxOd+9lzblxA3fiZnPpcvY/TKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQLJ0xfRtK4ide6FzdzHtvOVp6je/b0t2zs73ymkUIJFRgERGARIZBUhkFCCRUYBERgESGQVIZBQg+fl8Nm4VAG7hNAqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAiYwCJDIKkMgoQCKjAImMAiQyCpDIKEAiowCJjAIkMgqQyChAIqMAyT+DK7hBfYD72gAAAABJRU5ErkJggg=='

encoded_string = "your Base64-encoded string here"
length = len(a)
print(f"Length of Base64-encoded string: {length} characters")